/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    'IFluent:scaleFit16Regular': typeof import('~icons/fluent/scale-fit16-regular')['default']
    'ILucide:locateFixed': typeof import('~icons/lucide/locate-fixed')['default']
    'IPajamas:remove': typeof import('~icons/pajamas/remove')['default']
    'ITabler:rulerMeasure': typeof import('~icons/tabler/ruler-measure')['default']
    Measurements: typeof import('./src/components/PulsesViewerPaper/measurements.js')['default']
    MeasurementsMeta: typeof import('./src/components/PulsesViewer/MeasurementsMeta.vue')['default']
    PieChart: typeof import('./src/components/PieChart.js')['default']
    PulsesViewer: typeof import('./src/components/PulsesViewer/index.vue')['default']
    PulsesViewerPaper: typeof import('./src/components/PulsesViewerPaper/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shader2d: typeof import('./src/components/shader-2d.vue')['default']
    Store: typeof import('./src/components/PulsesViewerPaper/store.js')['default']
    UseMeasurements: typeof import('./src/components/PulsesViewer/useMeasurements.js')['default']
    UsePanZoom: typeof import('./src/components/PulsesViewerPaper/usePanZoom.js')['default']
    UsePaper: typeof import('./src/components/PulsesViewerPaper/usePaper.js')['default']
  }
}
